# Generated by Django 5.1.4 on 2024-12-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_pendingrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrating',
            name='delta',
            field=models.BooleanField(default=False),
        ),
    ]
