# Generated by Django 5.1.4 on 2024-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_pendingrating_delta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrating',
            name='delta',
        ),
        migrations.AddField(
            model_name='pendingrating',
            name='last_rate',
            field=models.IntegerField(default=0),
        ),
    ]
