# Generated by Django 5.1.4 on 2024-12-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_pendingrating_delta_pendingrating_last_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrating',
            name='last_rate',
            field=models.IntegerField(default=-1),
        ),
    ]
